server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:Michael-D-Sun/microservicecloud-config.git #GitHub上面的git仓库名字
          uri: https://github.com/Michael-D-Sun/microservicecloud-config.git


